export const API = Object.freeze({
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    ME: '/auth/me',
  },
  ARTICLES: {
    BASE: '/articles',
    BY_ID: (id) => `/articles/${id}`,
  },
  EDITAIS: {
    BASE: '/editais',
    ACTIVE: '/editais/active',
    BY_ID: (id) => `/editais/${id}`,
    FAVORITE: (id) => `/editais/${id}/favorite`,
    FAVORITES: '/editais/favorites',
  },
  CLASSIFIEDS: {
    BASE: '/classifieds',
    BY_ID: (id) => `/classifieds/${id}`,
    PENDING: '/classifieds/pending',
    MY: '/classifieds/my',
    MODERATE: (id) => `/classifieds/${id}/moderate`,
    FAVORITE: (id) => `/classifieds/${id}/favorite`,
  },
  EDITAIS_FOMENTO: {
    BASE: '/editais-fomento',
    BY_ID: (id) => `/editais-fomento/${id}`,
    FAVORITE: (id) => `/editais-fomento/${id}/favorite`,
    FAVORITES: '/editais-fomento/favorites',
    ESTADOS: '/editais-fomento/estados',
    STATS: '/editais-fomento/stats',
  },
  USERS: {
    BASE: '/users',
    BY_ID: (id) => `/users/${id}`,
  },
  COURSES: {
    BASE: '/courses',
    BY_ID: (id) => `/courses/${id}`,
    MODULES: (courseId) => `/courses/${courseId}/modules`,
    MODULE_BY_ID: (courseId, moduleId) => `/courses/${courseId}/modules/${moduleId}`,
    LESSONS: (courseId, moduleId) => `/courses/${courseId}/modules/${moduleId}/lessons`,
    LESSON_BY_ID: (courseId, moduleId, lessonId) => `/courses/${courseId}/modules/${moduleId}/lessons/${lessonId}`,
    VIDEO_STATUS: (lessonId) => `/courses/lessons/${lessonId}/video-status`,
    COMMENTS: (lessonId) => `/courses/lessons/${lessonId}/comments`,
    COMMENT_BY_ID: (commentId) => `/courses/comments/${commentId}`,
    COMMENT_REPLIES: (commentId) => `/courses/comments/${commentId}/replies`,
    COMMENTS_PENDING: '/courses/comments/pending',
    COMMENT_MODERATE: (commentId) => `/courses/comments/${commentId}/moderate`,
    LESSON_COMPLETE: (lessonId) => `/courses/lessons/${lessonId}/complete`,
    COURSE_PROGRESS: (courseId) => `/courses/${courseId}/progress`,
  },
});
