// Dados de demonstracao para visualizacao do layout quando as APIs estao vazias
// Remover este arquivo quando houver dados reais no backend

export const MOCK_ARTICLES = [
  {
    id: 'demo-1',
    title: 'Brasil investe R$ 2,5 bilhoes em programa nacional de inteligencia artificial',
    headline: 'Governo federal anuncia maior pacote de investimentos em IA da historia do pais',
    summary: 'O programa contempla criacao de centros de pesquisa em 12 estados, bolsas para pesquisadores e parcerias com universidades publicas. A expectativa e que o Brasil se torne referencia em IA aplicada a agricultura e saude publica ate 2028.',
    content: '<p>O Ministerio da Ciencia, Tecnologia e Inovacao anunciou nesta semana o maior pacote de investimentos em Inteligencia Artificial ja realizado no Brasil.</p><p>O programa, batizado de "IA Brasil 2028", preve a criacao de 12 centros de excelencia em pesquisa distribuidos por todas as regioes do pais, alem de 5.000 bolsas de mestrado e doutorado na area.</p><p>Segundo o ministro, o foco principal sera em aplicacoes praticas de IA para resolver problemas brasileiros, como otimizacao de safras agricolas, diagnostico medico em regioes remotas e combate ao desmatamento.</p><h2>Parcerias internacionais</h2><p>O programa tambem inclui acordos de cooperacao com universidades dos Estados Unidos, Alemanha e Coreia do Sul para transferencia de tecnologia e intercambio de pesquisadores.</p>',
    category: 'NEWS',
    featured: true,
    featuredImageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=450&fit=crop',
    publishedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    author: { name: 'Ana Carolina Ribeiro' },
    keywords: ['inteligencia artificial', 'tecnologia', 'investimento', 'pesquisa'],
    views: 1240,
  },
  {
    id: 'demo-2',
    title: 'Startup brasileira desenvolve sensor que detecta contaminacao em agua em tempo real',
    headline: 'Tecnologia usa nanotubos de carbono e pode revolucionar o monitoramento hidrico',
    summary: 'A HidroTech, de Campinas, criou um dispositivo portatil capaz de identificar mais de 50 tipos de contaminantes em menos de 30 segundos.',
    content: '<p>Uma startup de Campinas (SP) esta chamando atencao do mercado global com um sensor revolucionario para analise de qualidade da agua.</p>',
    category: 'REPORT',
    featuredImageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&h=450&fit=crop',
    publishedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    author: { name: 'Pedro Henrique Santos' },
    keywords: ['startup', 'agua', 'sensor', 'nanotecnologia'],
    views: 856,
  },
  {
    id: 'demo-3',
    title: 'Pesquisadores da USP criam vacina contra dengue com eficacia de 95%',
    headline: 'Resultados da fase 3 de testes clinicos foram publicados na revista Nature',
    summary: 'A nova vacina utiliza tecnologia de RNA mensageiro e mostrou protecao contra os quatro sorotipos do virus da dengue.',
    content: '<p>Pesquisadores do Instituto de Ciencias Biomedicas da USP publicaram resultados promissores da vacina brasileira contra dengue.</p>',
    category: 'NEWS',
    featuredImageUrl: 'https://images.unsplash.com/photo-1584036561566-baf8f5f1b144?w=800&h=450&fit=crop',
    publishedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    author: { name: 'Mariana Costa' },
    keywords: ['saude', 'vacina', 'dengue', 'pesquisa'],
    views: 2100,
  },
  {
    id: 'demo-4',
    title: 'Como a energia solar esta transformando comunidades rurais no Nordeste',
    headline: 'Programa de microgrids solares ja atende mais de 200 familias no sertao',
    summary: 'Projeto piloto mostra que energia limpa pode reduzir custos em ate 70% e gerar renda para agricultores familiares.',
    content: '<p>Um projeto inovador de energia solar descentralizada esta mudando a realidade de comunidades isoladas no sertao nordestino.</p>',
    category: 'REPORT',
    featuredImageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=450&fit=crop',
    publishedAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    author: { name: 'Lucas Oliveira' },
    keywords: ['energia solar', 'sustentabilidade', 'nordeste'],
    views: 645,
  },
  {
    id: 'demo-5',
    title: '"A educacao precisa abracar a tecnologia, nao teme-la", diz ministra',
    headline: 'Em entrevista exclusiva, ministra fala sobre o futuro da educacao digital no Brasil',
    summary: 'A ministra da Educacao discutiu os planos do governo para integrar ferramentas de IA nas escolas publicas ate 2027.',
    content: '<p>Em entrevista exclusiva ao Jornal O Inovador, a ministra da Educacao detalhou os planos do governo para a transformacao digital das escolas publicas brasileiras.</p>',
    category: 'INTERVIEW',
    featuredImageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&h=450&fit=crop',
    publishedAt: new Date(Date.now() - 48 * 3600000).toISOString(),
    author: { name: 'Fernanda Lima' },
    keywords: ['educacao', 'tecnologia', 'politica publica'],
    views: 980,
  },
  {
    id: 'demo-6',
    title: 'O papel das universidades publicas na inovacao tecnologica brasileira',
    headline: null,
    summary: 'Analise mostra que 70% das patentes de tecnologia no Brasil tem origem em universidades federais e estaduais.',
    content: '<p>Um levantamento inedito realizado pelo Observatorio da Inovacao revela o papel central das universidades publicas no ecossistema de inovacao do Brasil.</p>',
    category: 'ANALYSIS',
    featuredImageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&h=450&fit=crop',
    publishedAt: new Date(Date.now() - 72 * 3600000).toISOString(),
    author: { name: 'Roberto Campos' },
    keywords: ['universidade', 'patentes', 'inovacao'],
    views: 432,
  },
  {
    id: 'demo-7',
    title: 'Precisamos repensar o modelo de financiamento da pesquisa cientifica',
    headline: null,
    summary: 'O modelo atual de editais competitivos favorece areas consolidadas e dificulta a inovacao em campos emergentes.',
    content: '<p>O financiamento da pesquisa cientifica no Brasil precisa de uma reforma estrutural.</p>',
    category: 'OPINION',
    featuredImageUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=450&fit=crop',
    publishedAt: new Date(Date.now() - 96 * 3600000).toISOString(),
    author: { name: 'Prof. Maria Helena Souza' },
    keywords: ['editorial', 'financiamento', 'pesquisa'],
    views: 312,
  },
  {
    id: 'demo-8',
    title: 'A nova geracao de empreendedores esta mudando a cara da tecnologia no Brasil',
    headline: null,
    summary: 'Editorial sobre o crescimento do ecossistema de startups brasileiras e os desafios que ainda precisam ser superados.',
    content: '<p>Nos ultimos cinco anos, o ecossistema de startups brasileiro cresceu de forma impressionante.</p>',
    category: 'EDITORIAL',
    featuredImageUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&h=450&fit=crop',
    publishedAt: new Date(Date.now() - 120 * 3600000).toISOString(),
    author: { name: 'Equipe Editorial' },
    keywords: ['startups', 'empreendedorismo', 'tecnologia'],
    views: 567,
  },
];

export const MOCK_CLASSIFIEDS = [
  {
    id: 'cls-1',
    title: 'Estagio em Desenvolvimento Full Stack - React/Node.js',
    description: 'Vaga de estagio para estudantes de Ciencia da Computacao ou areas afins. Bolsa de R$ 2.000 + beneficios.',
    category: 'ESTAGIO',
    city: 'Sao Paulo',
    state: 'SP',
    imageUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=250&fit=crop',
    createdAt: new Date(Date.now() - 6 * 3600000).toISOString(),
  },
  {
    id: 'cls-2',
    title: 'Vaga para Pesquisador em Inteligencia Artificial',
    description: 'Posicao CLT em centro de pesquisa. Doutorado em IA, ML ou areas correlatas. Salario competitivo.',
    category: 'EMPREGO',
    city: 'Campinas',
    state: 'SP',
    imageUrl: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=250&fit=crop',
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: 'cls-3',
    title: 'Congresso Brasileiro de Inovacao Tecnologica 2026',
    description: 'Inscricoes abertas para o maior evento de inovacao do Brasil. 3 dias de palestras, workshops e networking.',
    category: 'EVENTO',
    city: 'Brasilia',
    state: 'DF',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=250&fit=crop',
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    id: 'cls-4',
    title: 'Microscopio Eletronico de Varredura - Semi-novo',
    description: 'Equipamento em otimo estado, com manutencao em dia. Ideal para laboratorios de pesquisa.',
    category: 'EQUIPAMENTO',
    city: 'Rio de Janeiro',
    state: 'RJ',
    imageUrl: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?w=400&h=250&fit=crop',
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
  {
    id: 'cls-5',
    title: 'Publicacao de Artigo - Revista de Biotecnologia Aplicada',
    description: 'Chamada aberta para submissao de artigos. Edicao especial sobre biotecnologia e saude publica.',
    category: 'PUBLICACAO_CIENTIFICA',
    city: 'Belo Horizonte',
    state: 'MG',
    imageUrl: 'https://images.unsplash.com/photo-1532153975070-2e9ab71f1b14?w=400&h=250&fit=crop',
    createdAt: new Date(Date.now() - 72 * 3600000).toISOString(),
  },
  {
    id: 'cls-6',
    title: 'Desenvolvedor Python Senior - Remoto',
    description: 'Oportunidade para trabalhar com data science e machine learning em startup de healthtech.',
    category: 'TECNOLOGIA',
    city: 'Remoto',
    state: '',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400&h=250&fit=crop',
    createdAt: new Date(Date.now() - 96 * 3600000).toISOString(),
  },
];
