export const ROUTES = Object.freeze({
  HOME: '/',
  ARTICLES: '/artigos',
  ARTICLE_DETAIL: '/artigos/:id',
  EDITAIS: '/editais',
  EDITAL_DETAIL: '/editais/:id',
  EDITAIS_FOMENTO: '/editais-fomento',
  EDITAL_FOMENTO_DETAIL: '/editais-fomento/:id',
  CLASSIFIEDS: '/classificados',
  CLASSIFIED_DETAIL: '/classificados/:id',
  COURSES: '/cursos',
  COURSE_DETAIL: '/cursos/:id',
  COURSE_LESSON: '/cursos/:courseId/aulas/:lessonId',
  AUTHOR: '/autor/:authorId',
  LOGIN: '/entrar',
  REGISTER: '/cadastro',

  DASHBOARD: '/painel',
  MY_CLASSIFIEDS: '/painel/meus-classificados',
  CREATE_CLASSIFIED: '/painel/classificados/novo',
  EDIT_CLASSIFIED: '/painel/classificados/:id/editar',
  FAVORITE_ARTICLES: '/painel/artigos-favoritos',
  FAVORITE_EDITAIS: '/painel/editais-favoritos',
  PROFILE: '/painel/perfil',

  ADMIN: '/admin',
  ADMIN_ARTICLES: '/admin/artigos',
  ADMIN_CREATE_ARTICLE: '/admin/artigos/novo',
  ADMIN_EDIT_ARTICLE: '/admin/artigos/:id/editar',
  ADMIN_EDITAIS_FOMENTO: '/admin/editais-fomento',
  ADMIN_EDIT_EDITAL_FOMENTO: '/admin/editais-fomento/:id/editar',
  ADMIN_CLASSIFIEDS: '/admin/classificados',
  ADMIN_COURSES: '/admin/cursos',
  ADMIN_CREATE_COURSE: '/admin/cursos/novo',
  ADMIN_EDIT_COURSE: '/admin/cursos/:id/editar',
  ADMIN_COURSE_MODULES: '/admin/cursos/:courseId/modulos',
  ADMIN_CREATE_MODULE: '/admin/cursos/:courseId/modulos/novo',
  ADMIN_EDIT_MODULE: '/admin/cursos/:courseId/modulos/:moduleId/editar',
  ADMIN_MODULE_LESSONS: '/admin/cursos/:courseId/modulos/:moduleId/aulas',
  ADMIN_CREATE_LESSON: '/admin/cursos/:courseId/modulos/:moduleId/aulas/nova',
  ADMIN_EDIT_LESSON: '/admin/cursos/:courseId/modulos/:moduleId/aulas/:lessonId/editar',
  ADMIN_LESSON_COMMENTS: '/admin/cursos/aulas/:lessonId/comentarios',
  ADMIN_ARTICLE_COMMENTS: '/admin/artigos/comentarios',
  ADMIN_PENDING_COMMENTS: '/admin/comentarios',
  ADMIN_USERS: '/admin/usuarios',
});
