export const ROUTES = Object.freeze({
  HOME: '/',
  ARTICLES: '/artigos',
  ARTICLE_DETAIL: '/artigos/:id',
  EDITAIS: '/editais',
  EDITAL_DETAIL: '/editais/:id',
  EDITAIS_FOMENTO: '/editais-fomento',
  EDITAL_FOMENTO_DETAIL: '/editais-fomento/:id',
  CLASSIFIEDS: '/classificados',
  CLASSIFIED_DETAIL: '/classificados/:id',
  LOGIN: '/entrar',
  REGISTER: '/cadastro',

  DASHBOARD: '/painel',
  MY_CLASSIFIEDS: '/painel/meus-classificados',
  CREATE_CLASSIFIED: '/painel/classificados/novo',
  EDIT_CLASSIFIED: '/painel/classificados/:id/editar',
  FAVORITE_EDITAIS: '/painel/editais-favoritos',
  PROFILE: '/painel/perfil',

  ADMIN: '/admin',
  ADMIN_ARTICLES: '/admin/artigos',
  ADMIN_CREATE_ARTICLE: '/admin/artigos/novo',
  ADMIN_EDIT_ARTICLE: '/admin/artigos/:id/editar',
  ADMIN_EDITAIS: '/admin/editais',
  ADMIN_CREATE_EDITAL: '/admin/editais/novo',
  ADMIN_EDIT_EDITAL: '/admin/editais/:id/editar',
  ADMIN_CLASSIFIEDS: '/admin/classificados',
  ADMIN_USERS: '/admin/usuarios',
});
